export let configData = {
    "mikanHost": "https://mikanani.me",
    "tmdbApi": "https://api.themoviedb.org",
    "tmdbApiKey": "",
    "tmdbImage": "https://image.tmdb.org",
    "tmdbAnime": true,
    "downloadToolType": "115",
    "downloadRetry": 3,
    "downloadPathTemplate": "",
    "ovaDownloadPathTemplate": "",
    "delayedDownload": 0,
    "rssSleepMinutes": 15,
    "rename": true,
    "rss": true,
    "rssTimeout": 20,
    "fileExist": false,
    "offset": false,
    "titleYear": false,
    "autoDisabled": false,
    "skip5": true,
    "standbyRss": false,
    "coexist": false,
    "logsMax": 128,
    "debug": false,
    "procrastinatingMasterOnly": true,
    "proxy": false,
    "proxyHost": "",
    "proxyPort": 8080,
    "proxyUsername": "",
    "proxyPassword": "",
    "login": {
        "username": "admin",
        "password": ""
    },
    "multiLoginForbidden": true,
    "loginEffectiveHours": 3,
    "exclude": [
        "720[Pp]",
        "\\d-\\d",
        "合集",
        "特别篇"
    ],
    "importExclude": false,
    "enabledExclude": false,
    "bgmJpName": false,
    "tmdb": false,
    "tmdbId": false,
    "tmdbIdPlexMode": false,
    "tmdbLanguage": "zh-CN",
    "ipWhitelist": false,
    "ipWhitelistStr": "",
    "omit": true,
    "bgmTokenType": "INPUT",
    "bgmToken": "",
    "bgmAppID": "",
    "bgmAppSecret": "",
    "bgmRefreshToken": "",
    "bgmRedirectUri": "",
    "apiKey": "",
    "downloadNew": false,
    "renameTemplate": "[${subgroup}] ${title} S${seasonFormat}E${episodeFormat}",
    "renameDelYear": false,
    "renameDelTmdbId": false,
    "verifyLoginIp": false,
    "notificationTemplate": "",
    "bgmImage": "large",
    "customCss": "",
    "customJs": "",
    "customEpisode": false,
    "customEpisodeStr": "",
    "customEpisodeGroupIndex": 0,
    "procrastinating": false,
    "procrastinatingDay": 14,
    "updateTotalEpisodeNumber": false,
    "forceUpdateTotalEpisodeNumber": false,
    "downloadTimeout": 60,
    "notificationConfigList": [],
    "copyMasterToStandby": false,
    "sortType": "SCORE",
    "replace": false,
    "maxFileNameLength": 0,
    "limitLoginAttempts": true,
    "gitInfo": {
        "branch": "",
        "shortCommitId": "",
        "commitId": ""
    },
    "reverseProxyTrustIpListEnabled": false,
    "reverseProxyTrustIpList": [
        "127.0.0.1"
    ],
    "bgmApi": "https://api.bgm.tv",
    "allowCors": false,
    "uuid": ""
}